### PR TITLE
Hides H4 headings from TOC, #22

### LINKED ISSUE #22: Remove h4 headings from the in-page contents menu
The material theme we're using provides a contents menu for each page. It is automatically populated with the headings from the page, h2 > h4 (at least). For this site, we only want h2 and h3 headings including in the contents menu.

Example: https://techwritertoolkit.com/consultant/core-values/
The contents menu there includes all the "Example" h4 headings, which looks messy.

Customize the theme to only include h2 and h3 headings.

Refer to guidance in the theme docs: https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme. This task involves overriding a partial.

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Fixes #22

Based on https://github.com/squidfunk/mkdocs-material/pull/450

### CODE REVIEW

**Comment by StarfallProjects** [comment]
Hi Gaurav!
Thanks for your contributions :-)

This one needs another look. Your solution works, but the better way would be to override the template, rather than extend the stylesheet (the difference is never adding the h4 vs. hiding them retroactively) 

Let me know if you want to have a go at that.

**Review by StarfallProjects — CHANGES_REQUESTED** [review]
Should be overriding the partial rather than extending the stylesheet

**Comment by gaurav-nelson** [comment]
Thanks for reviewing @StarfallProjects 

This one looked easy to handle. I'll checkout how to deal with this using partials.

**Comment by StarfallProjects** [comment]
Let me know if you need a hand, or if you'd prefer someone else to pick it up :-)

**Comment by gaurav-nelson** [comment]
Closing this, I am not sure how to handle this with partials. 👍

**Pull request closed without merging**
